name: Deploy to GitHub Pages

on: 
  # Dispara a action toda vez que houver um push na branch main
  push: 
    branches: [ main ]
  # Permite rodar o script manualmente na aba Actions do GitHub
  workflow_dispatch:

# Permissões DevSecOps necessárias para o GitHub Pages ler e publicar
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      
      - name: Instalação e Build do Astro
        uses: withastro/action@v3
        # Se o seu projeto não estiver na raiz do repositório, 
        # descomente as linhas abaixo e aponte o caminho
        # with:
        #   path: ./pasta-do-projeto

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4